apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-argo-application
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/leeez0128/k8s-argocd-node-app-config.git
    targetRevision: HEAD
    path: k8s-node-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
