apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8s-node-app
spec:
    selector:
        matchLabels:
            app: k8s-node-app
    replicas: 2
    template:
        metadata:
            labels:
                app: k8s-node-app
        spec:
            containers:
                - name: k8s-node-app
                  image: rominowujeel/gitops-node-example:1
                  ports:
                      - containerPort: 3000
