apiVersion: v1
kind: Service
metadata:
    name: k8s-node-app-service
spec:
    selector:
        app: k8s-node-app
    ports:
        - port: 3000
          protocol: TCP
          targetPort: 3000
    type: LoadBalancer
